### PR TITLE
rosinstall and build script to ease working with dependencies

### PR DESCRIPTION
**Pull request by martinmagnusson**
Attempting a script to install and build all dependencies, for melodic.
This is still a WIP. It works for me up to the point of `CMake Error at /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:271 (message):  Could not find 'share/graph_map/cmake/graph_map-msg-paths.cmake'`

### CODE REVIEW

**Comment by martinmagnusson** [comment]
Commit 4d93811 also makes some changes to fix that graph_map's custom messages were moved

**Comment by MalcolmMielle** [comment]
I converted the PR to a draft since it's a WIP :). Change it to a normal PR when it's ready

**Comment by martinmagnusson** [comment]
Maybe I could put this in its own branch of https://github.com/MalcolmMielle/Auto-Complete-Graph instead? That might make it easier for the UCL people to try it out

**Comment by MalcolmMielle** [comment]
I've added you as a collaborator and protected the master branch of the repo, so nothing can be directly pushed.
This way, you should now be able to create a branch directly on the project for UCL people :).

Otherwise, people at UCL can add your fork as a remote, pull your changes, and work on top of it. However, I think the workflow is usually that you would push a PR with isolated change that would be merged in :). From my point of view, this PR could be merged since it concerned the dependency install and that seems to be working (I have only put as a draft because you said it was a work in progress). The next PR would be concerned with fixing the namespace error ;).

**Comment by martinmagnusson** [comment]
True. I removed commit 4d93811 with changes to the source code, so that this pull request only contains `rosinstall` and `build.sh` which should not break anything.

**Comment by MalcolmMielle** [comment]
Should I merge it? It looks good to me

**Comment by martinmagnusson** [comment]
Yes, let's do that

**Pull request merged**
